import type { RegulationCode } from './types';

/* ── Saudi building codes reference data ── */
export const BUILDING_CODES: RegulationCode[] = [
  {
    code: 'س111',
    nameAr: 'فيلات مستقلة / أدوار سكنية',
    landType: 'سكني',
    allowedUses: ['فيلا منفصلة', 'فيلا متلاصقة', 'أدوار سكنية'],
    maxFloors: 2,
    hasAnnex: true,
    annexPct: 0.5,
    groundCoverageGround: 0.60,
    groundCoverageUpper: 0.60,
    minStreetWidth: 10,
    setbacks: {
      mainStreet: '1/5 عرض الشارع بحد أدنى 2م',
      mainStreetValue: 0,
      neighbor: 2,
      secondaryStreet: '1/5 عرض الشارع بحد أدنى 2م',
      secondaryStreetFormula: 'fraction',
      secondaryStreetMin: 2,
    },
    parkingRules: [
      { useType: 'سكني', condition: 'per_unit_small', threshold: 180, spots: 1 },
      { useType: 'سكني', condition: 'per_unit_large', threshold: 180, spots: 2 },
    ],
  },
  {
    code: 'س112',
    nameAr: 'مبانٍ سكنية متعددة الأدوار',
    landType: 'سكني',
    allowedUses: ['عمارة سكنية', 'شقق سكنية', 'أدوار سكنية'],
    maxFloors: 4,
    hasAnnex: false,
    annexPct: 0,
    groundCoverageGround: 0.65,
    groundCoverageUpper: 0.65,
    minStreetWidth: 12,
    setbacks: {
      mainStreet: '1/5 عرض الشارع بحد أدنى 3م',
      mainStreetValue: 0,
      neighbor: 2,
      secondaryStreet: '1/5 عرض الشارع بحد أدنى 2م',
      secondaryStreetFormula: 'fraction',
      secondaryStreetMin: 2,
    },
    parkingRules: [
      { useType: 'سكني', condition: 'per_unit_small', threshold: 120, spots: 1 },
      { useType: 'سكني', condition: 'per_unit_large', threshold: 120, spots: 2 },
    ],
  },
  {
    code: 'س121',
    nameAr: 'مبانٍ سكنية مرتفعة',
    landType: 'سكني',
    allowedUses: ['برج سكني', 'عمارة سكنية مرتفعة', 'شقق سكنية فاخرة'],
    maxFloors: 8,
    hasAnnex: false,
    annexPct: 0,
    groundCoverageGround: 0.55,
    groundCoverageUpper: 0.55,
    minStreetWidth: 15,
    setbacks: {
      mainStreet: '1/5 عرض الشارع بحد أدنى 4م',
      mainStreetValue: 0,
      neighbor: 3,
      secondaryStreet: '1/5 عرض الشارع بحد أدنى 3م',
      secondaryStreetFormula: 'fraction',
      secondaryStreetMin: 3,
    },
    parkingRules: [
      { useType: 'سكني', condition: 'per_unit_small', threshold: 120, spots: 1 },
      { useType: 'سكني', condition: 'per_unit_large', threshold: 120, spots: 2 },
    ],
    depthRule: 'عمق القطعة لا يقل عن 20م',
  },
  {
    code: 'م111',
    nameAr: 'استخدام مختلط (سكني + تجاري)',
    landType: 'تجاري',
    allowedUses: ['محلات تجارية', 'مكاتب', 'شقق سكنية', 'استخدام مختلط'],
    maxFloors: 5,
    hasAnnex: false,
    annexPct: 0,
    groundCoverageGround: 0.70,
    groundCoverageUpper: 0.65,
    minStreetWidth: 15,
    setbacks: {
      mainStreet: '3م ثابت',
      mainStreetValue: 3,
      neighbor: 0,
      secondaryStreet: '1/5 عرض الشارع بحد أدنى 2م',
      secondaryStreetFormula: 'fraction',
      secondaryStreetMin: 2,
    },
    parkingRules: [
      { useType: 'تجاري', condition: 'per_sqm', sqmPerSpot: 30, spots: 1 },
      { useType: 'سكني',  condition: 'per_unit_small', threshold: 120, spots: 1 },
      { useType: 'سكني',  condition: 'per_unit_large', threshold: 120, spots: 2 },
    ],
  },
  {
    code: 'ت111',
    nameAr: 'تجاري خدمي',
    landType: 'تجاري',
    allowedUses: ['محلات تجارية', 'مطاعم', 'بنوك', 'خدمات'],
    maxFloors: 3,
    hasAnnex: false,
    annexPct: 0,
    groundCoverageGround: 0.75,
    groundCoverageUpper: 0.70,
    minStreetWidth: 15,
    setbacks: {
      mainStreet: '3م ثابت',
      mainStreetValue: 3,
      neighbor: 0,
      secondaryStreet: '1/5 عرض الشارع بحد أدنى 2م',
      secondaryStreetFormula: 'fraction',
      secondaryStreetMin: 2,
    },
    parkingRules: [
      { useType: 'تجاري', condition: 'per_sqm', sqmPerSpot: 25, spots: 1 },
    ],
  },
  {
    code: 'م121',
    nameAr: 'مختلط مع مكاتب',
    landType: 'تجاري',
    allowedUses: ['مكاتب', 'محلات تجارية', 'شقق فندقية', 'استخدام مختلط'],
    maxFloors: 10,
    hasAnnex: false,
    annexPct: 0,
    groundCoverageGround: 0.65,
    groundCoverageUpper: 0.60,
    minStreetWidth: 20,
    setbacks: {
      mainStreet: '4م ثابت',
      mainStreetValue: 4,
      neighbor: 3,
      secondaryStreet: '1/5 عرض الشارع بحد أدنى 3م',
      secondaryStreetFormula: 'fraction',
      secondaryStreetMin: 3,
    },
    parkingRules: [
      { useType: 'مكاتب',  condition: 'per_sqm', sqmPerSpot: 30, spots: 1 },
      { useType: 'تجاري',  condition: 'per_sqm', sqmPerSpot: 25, spots: 1 },
    ],
    depthRule: 'عمق القطعة لا يقل عن 25م',
  },
];

export function getBuildingCode(code: string): RegulationCode | null {
  return BUILDING_CODES.find(c => c.code === code) ?? null;
}
